# Generated by Django 4.2.1 on 2023-08-21 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0004_deleted_entries'),
    ]

    operations = [
        migrations.AddField(
            model_name='entries',
            name='feedback',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
