# Generated by Django 4.2.1 on 2023-09-06 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0005_entries_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='forms',
            name='department',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
